import Head from "next/head";
import Nav from "../components/Nav";
import Image from "next/image";
import HouseListing from "../components/houseListings";

export default function Explore() {
  return (
    <main className="mb-28 mt-6">
      <Head>
        <title>Explore Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Nav />

      <h1 className="text-4xl mb-12">Explore</h1>
      <h2 className="font-bold ml-3 text-xl mb-2">Categories</h2>
      <section className=" grid grid-cols-auto-fit">
        {/* first house */}
        <div className="flex flex-col items-start ml-6">
          <HouseListing />
          <h3 className="mt-2 text-lg font-medium">Houses for rent</h3>
        </div>
        {/* second house */}
        <div className="flex flex-col items-start">
          <HouseListing />
          <h3 className="mt-2 text-lg font-medium">Houses for sale</h3>
        </div>

      </section>
    </main>
  );
}
