import Head from "next/head";
import Nav from "../components/Nav";
import Image from "next/image";
import HouseListing from "../components/houseListings";
import { Swiper, SwiperSlide } from "swiper/react";
import "swiper/css";
import "swiper/css/pagination";
import { Pagination } from "swiper";

export default function Explore() {
  return (
    <main className="mb-52 mt-6 mx-3">
      <Head>
        <title>Explore Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />

      <h1 className="text-4xl mb-12 font-bold">Explore</h1>

      <h3 className="font-bold ml-3 text-xl mt-12 mb-4">Recommended</h3>

      <Swiper
        pagination={{
          dynamicBullets: true,
          clickable: true,
        }}
        modules={[Pagination]}
        className="mySwiper"
      >
        <SwiperSlide>
          <div className="w-full mx-auto text-center min-h-[30rem] rounded-lg mb-8 bg-[url('/house-images/exterior_1.jpeg')] bg-cover bg-no-repeat bg-center">
            <div className="w-full h-full flex flex-col items-start py-20">
              <h3 className="text-3xl font-bold bg-black ml-5">
                <span className="text-white">House For Rent In California</span>
              </h3>
              <h3 className=" text-3xl font-bold bg-white ml-5 mt-3 ">
                <span className="text-black">$2,400 / month</span>
              </h3>
            </div>
          </div>
        </SwiperSlide>

        <SwiperSlide>
          <div className="w-full mx-auto text-center min-h-[30rem] rounded-lg mb-8 bg-[url('/house-images/exterior_2.jpeg')] bg-cover bg-no-repeat bg-center">
            <div className="w-full h-full flex flex-col items-start py-20">
              <h3 className="text-3xl font-bold bg-black ml-5">
                <span className="text-white">House For Rent In Texas</span>
              </h3>
              <h3 className=" text-3xl font-bold bg-white ml-5 mt-3 ">
                <span className="text-black">$1,100 / month</span>
              </h3>
            </div>
          </div>
        </SwiperSlide>

        <SwiperSlide>
          <div className="w-full mx-auto text-center min-h-[30rem] rounded-lg mb-8 bg-[url('/house-images/exterior_3.jpeg')] bg-cover bg-no-repeat bg-center">
            <div className="w-full h-full flex flex-col items-start py-20">
              <h3 className="text-3xl font-bold bg-black ml-5">
                <span className="text-white">House For Rent In Florida</span>
              </h3>
              <h3 className=" text-3xl font-bold bg-white ml-5 mt-3 ">
                <span className="text-black">$1,600 / month</span>
              </h3>
            </div>
          </div>
        </SwiperSlide>
      </Swiper>

      <h2 className="font-bold ml-3 text-xl mt-20 mb-8">Categories</h2>
      <section className=" flex flex-row justify-around">
        {/* first house */}
        <div className="flex flex-col">
          <HouseListing />
          <h3 className="mt-2 text-lg font-medium">Houses for rent</h3>
        </div>
        {/* second house */}
        <div className="flex flex-col">
          <HouseListing />
          <h3 className="mt-2 text-lg font-medium">Houses for sale</h3>
        </div>
      </section>
    </main>
  );
}
