import Head from "next/head";

export default function Explore() {
  return (
    <main>
      <Head>
        <title>Explore Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-6xl">Explore</h1>
      <p>content here</p>
    </main>
  );
};
