import Head from "next/head";

export default function ForgotPassword() {
  return (
    <main>
      <Head>
        <title>Forgot Password</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-4xl">Forgot Password page</h1>
    </main>
  );
}
