import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useState, useEffect } from "react";
import { getAuth, signInWithEmailAndPassword } from "firebase/auth";
import { useRouter } from "next/router";
import { db } from "../firebase.config";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Zoom } from "react-toastify";

export default function Home() {
  const [isUserLoggedIn, setIsUserLoggedIn] = useState(false);
  const [formData, setFormData] = useState({
    email: "",
    password: "",
  });
  const router = useRouter();

  const onChange = (e) => {
    setFormData({
      ...formData,
      [e.target.id]: e.target.value,
    });
  };

  useEffect(() => {
    if (isUserLoggedIn) {
      router.push("/explore");
    }
  }, [router, isUserLoggedIn]);

  const onSubmit = async (e) => {
    e.preventDefault();

    const auth = getAuth();

    try {
      const userCredential = await signInWithEmailAndPassword(
        auth,
        formData.email,
        formData.password
      );

      toast.success("Signed in", {
        position: toast.POSITION.BOTTOM_CENTER,
      });

      setIsUserLoggedIn(true);

      setFormData({
        email: "",
        password: "",
      });
    } catch (error) {
      console.log(`${error.message}`);
      toast.error("Incorrect email or password", {
        position: toast.POSITION.BOTTOM_CENTER,
      });
    }
  };

  return (
    <main className="pt-12">
      <Head>
        <title>House Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ToastContainer
        pauseOnHover={false}
        transition={Zoom}
        hideProgressBar={true}
      />

      <section className="flex mt-4 mb-4 flex-col items-center">
        <h1 className=" text-6xl font-semibold ">Welcome Back!</h1>
        <br />

        <form onSubmit={onSubmit} className="flex flex-col items-center">
          <input
            className="rounded-lg py-2 w-72 focus:outline-gray-200 indent-8 transition duration-300 mt-4 bg-[url('/personIcon.svg')] bg-no-repeat bg-left"
            type="text"
            placeholder="Username or Email"
            onChange={onChange}
            value={formData.email}
            id="email"
          />
          <br />
          <input
            className="rounded-lg py-2 w-72 focus:outline-gray-200 indent-8 transition duration-300 bg-[url('/lockIcon.svg')] bg-no-repeat bg-left"
            type="password"
            placeholder="Password"
            onChange={onChange}
            value={formData.password}
            id="password"
          />
          <span className="ml-60 pt-2 hover:cursor-pointer text-gray-400 hover:text-green-400 transition duration-300">
            Forgot Password?
          </span>

          <button className="mt-8 mb-4 bg-green-500 rounded-lg py-2 px-2 w-72 text-white hover:bg-green-400 transition duration-500">
            Sign in
          </button>

          <span className="text-gray-500 text-xs">
            Not a user?{" "}
            <Link href="/signup">
              <span className="hover:text-green-400 duration-300 hover:cursor-pointer underline">
                Sign up
              </span>
            </Link>
          </span>
        </form>
      </section>

      <section className="flex flex-row justify-center pb-4">
        <div className=" border-b-2 w-1/4 border-gray-300 self-center "></div>
        <p className="px-4 self-center text-gray-500">or</p>
        <div className="border-b-2 w-1/4 border-gray-300 self-center"></div>
      </section>

      <section className="flex mt-4 flex-col items-center justify-center">
        <p>Sign in with</p>
        <div className="mt-6">
          <Image
            src={"/appleLogo.svg"}
            width={34}
            height={50}
            alt="google button"
            className="cursor-pointer"
          ></Image>
          <span className="mx-6"></span>
          <Image
            src={"/googleIcon.svg"}
            width={34}
            height={50}
            alt="google button"
            className="cursor-pointer"
          ></Image>
          <span className="mx-6"></span>
          <Image
            src={"/facebook.svg"}
            width={34}
            height={50}
            alt="google button"
            className="cursor-pointer"
          ></Image>
        </div>
      </section>
    </main>
  );
}
